// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.DB;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Server.DB.DataModel+AccountDb", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AccountPw")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("AccountId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Server.DB.DataModel+PlayerDb", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AccountId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PlayerId");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Server.DB.DataModel+ScoreDb", b =>
                {
                    b.Property<int>("ScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("FaultCount")
                        .HasColumnType("int");

                    b.Property<int>("FinalScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("GameDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Position")
                        .HasColumnType("longtext");

                    b.HasKey("ScoreId");

                    b.HasIndex("AccountId");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("Server.DB.DataModel+PlayerDb", b =>
                {
                    b.HasOne("Server.DB.DataModel+AccountDb", "Account")
                        .WithOne("Player")
                        .HasForeignKey("Server.DB.DataModel+PlayerDb", "AccountId");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Server.DB.DataModel+ScoreDb", b =>
                {
                    b.HasOne("Server.DB.DataModel+AccountDb", "Account")
                        .WithMany("Scores")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Server.DB.DataModel+AccountDb", b =>
                {
                    b.Navigation("Player");

                    b.Navigation("Scores");
                });
#pragma warning restore 612, 618
        }
    }
}
